pipeline:
  name: my-ci
  identifier: myci
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: checkout
        identifier: checkout
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      ./gradlew clean bootJar
                      java -jar build/libs/hello-world.jar
          buildIntelligence:
            enabled: false
