pipeline:
  name: my-ci
  identifier: myci
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  variables:
    - name: cdExecutionId
      type: String
      default: wsULKthXTQOhj2S31Vp5uQ
      value: <+input>
  stages:
    - stage:
        name: hello
        identifier: hello
        description: ""
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.mywindowsk8s
                    image: curlimages/curl:8.13.0
                    shell: Sh
                    source:
                      type: Inline
                      command: |
                        #!/bin/sh
                        set -ex

                        curl -X GET https://httpbin.org/get
          cloneCodebase: false
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.mywindowsk8s
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        delegateSelectors:
          - kubernetes-delegate
