pipeline:
  name: my-ci
  identifier: myci
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        repoName: account.harness-filestore
        build: <+input>
  stages:
    - stage:
        name: hello
        identifier: hello
        description: ""
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.mywindowsk8s
                    image: alpine:3.21.3
                    shell: Sh
                    command: echo "hello world"
          cloneCodebase: true
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.mywindowsk8s
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        delegateSelectors:
          - kubernetes-delegate
